### ISSUE TITLE
iOS build fails

### ISSUE THREAD

**Issue by Stephan221713** [adeprez/capacitor-user-agent#4]
- In versions 0.1.1 and 0.1.2 the XCode build on iOS fails.
- The error occurs in the file ios/Plugin/UserAgentPlugin.swift in line 31.
- The error message is "Cannot convert value of type 'Bool' to expected argument type 'String'".
- Changing `let reloadOnChange = call.getString("reloadOnChange") ?? false` to `let reloadOnChange = call.getBool("reloadOnChange") ?? false` fixes the build.
- I am not familiar with the internals of this repo, but given that "reloadOnChange" is a boolean flag in the public set method, getBool seems to make sense anyway.

I hope the fix is as simple as I think. Thank you for providing this package and keep up the good work.

**Comment by adeprez** [comment]
Thank you for your feedback Stephan, I will push a fix in a few hours

**Comment by adeprez** [comment]
Your solution was correct, thank you for your help!

Fixed in [version 0.1.3](https://github.com/adeprez/capacitor-user-agent/releases/tag/0.1.3), available on npm. It was failing on iOS on versions 0.1.1 and 0.1.2
